-- MySQL Script generated by MySQL Workbench
-- Παρ 24 Μαΐ 2019 03:44:15 μμ EEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`publisher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`publisher` (
  `pubName` VARCHAR(45) NOT NULL,
  `estYear` INT NOT NULL,
  `pubAddress` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pubName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Book` (
  `ISBN` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `pubYear` VARCHAR(45) NOT NULL,
  `numpages` VARCHAR(45) NOT NULL,
  `pubName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ISBN`),
  INDEX `fk_Book_1_idx` (`pubName` ASC),
  CONSTRAINT `fk_Book_1`
    FOREIGN KEY (`pubName`)
    REFERENCES `mydb`.`publisher` (`pubName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`member` (
  `memberID` INT NOT NULL,
  `MFirst` VARCHAR(45) NOT NULL,
  `MLast` VARCHAR(45) NOT NULL,
  `Street` VARCHAR(45) NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  `postalCode` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`memberID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`author` (
  `authID` INT NOT NULL,
  `AFirst` VARCHAR(45) NOT NULL,
  `ALast` VARCHAR(45) NOT NULL,
  `Abirthdate` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`authID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `categoryName` VARCHAR(45) NOT NULL,
  `supercategoryName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`categoryName`),
  INDEX `fk_category_category1_idx` (`supercategoryName` ASC),
  CONSTRAINT `fk_category_category1`
    FOREIGN KEY (`supercategoryName`)
    REFERENCES `mydb`.`category` (`categoryName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`copies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`copies` (
  `ISBN` INT NOT NULL,
  `copyNr` VARCHAR(45) NOT NULL,
  `shelf` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ISBN`, `copyNr`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employee` (
  `empID` INT NOT NULL,
  `EFisrt` VARCHAR(45) NOT NULL,
  `ELast` VARCHAR(45) NOT NULL,
  `salary` VARCHAR(45) NULL,
  PRIMARY KEY (`empID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`written_by`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`written_by` (
  `ISBN` INT NOT NULL,
  `authID` INT NOT NULL,
  INDEX `fk_written_by_2_idx` (`authID` ASC),
  CONSTRAINT `fk_written_by_1`
    FOREIGN KEY (`ISBN`)
    REFERENCES `mydb`.`Book` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_written_by_2`
    FOREIGN KEY (`authID`)
    REFERENCES `mydb`.`author` (`authID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`belongs_to`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`belongs_to` (
  `ISBN` INT NOT NULL,
  `categoryName` VARCHAR(45) NOT NULL,
  INDEX `fk_belongs_to_2_idx` (`categoryName` ASC),
  CONSTRAINT `fk_belongs_to_1`
    FOREIGN KEY (`ISBN`)
    REFERENCES `mydb`.`Book` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_belongs_to_2`
    FOREIGN KEY (`categoryName`)
    REFERENCES `mydb`.`category` (`categoryName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`borrows`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`borrows` (
  `member_memberID` INT NOT NULL,
  `copies_ISBN` INT NOT NULL,
  `copies_copyNr` VARCHAR(45) NOT NULL,
  `date_of_borrowing` VARCHAR(45) NOT NULL,
  `date_of_return` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`copies_copyNr`, `date_of_borrowing`, `member_memberID`, `copies_ISBN`),
  INDEX `fk_member_has_copies_member1_idx` (`member_memberID` ASC),
  INDEX `fk_borrows_ISBN_idx` (`copies_ISBN` ASC),
  INDEX `fk_borrows_ISBN_and_copyNr_idx` (`copies_ISBN` ASC, `copies_copyNr` ASC),
  CONSTRAINT `fk_borrows_member1`
    FOREIGN KEY (`member_memberID`)
    REFERENCES `mydb`.`member` (`memberID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_borrows_ISBN`
    FOREIGN KEY (`copies_ISBN`)
    REFERENCES `mydb`.`Book` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_borrows_ISBN_and_copyNr`
    FOREIGN KEY (`copies_ISBN` , `copies_copyNr`)
    REFERENCES `mydb`.`copies` (`ISBN` , `copyNr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`permanent_employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`permanent_employee` (
  `empID` INT NOT NULL,
  `HiringDate` VARCHAR(45) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`temporary_employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`temporary_employee` (
  `empID` INT NOT NULL,
  `ContactNr` VARCHAR(45) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`has_copies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`has_copies` (
  `ISBN` INT NOT NULL,
  `copyNr` VARCHAR(45) NOT NULL,
  CONSTRAINT `fk_has_copies_1`
    FOREIGN KEY (`ISBN`)
    REFERENCES `mydb`.`Book` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_has_copies_2`
    FOREIGN KEY (`ISBN` , `copyNr`)
    REFERENCES `mydb`.`copies` (`ISBN` , `copyNr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
